---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: brew-instance
    image: test-brew
    pre_build_instance: true
  - name: go-instance
    image: test-go
    pre_build_instance: true
  - name: node-instance
    image: test-node
    pre_build_instance: true
  - name: python2-instance
    image: test-python2
    pre_build_instance: true
  - name: python3-instance
    image: test-python3
    pre_build_instance: true
  - name: rbenv-instance
    image: test-rbenv
    pre_build_instance: true
  - name: rvm-instance
    image: test-rvm
    pre_build_instance: true
provisioner:
  name: ansible
  options:
    vv: True
  log: true
  env:
    ANSIBLE_ROLES_PATH: ../../../ansible/roles
  inventory:
    host_vars:
      python2-instance:
        var_omniversion:
          auto: true
          pip:
            executables:
              - pip
            venv:
              - /pip/test1/test-env
              - /pip/test2/test-env
      python3-instance:
        var_omniversion:
          auto: true
          pip:
            executables:
              - pip3
            venv:
              - /pip/test1/test-env
              - /pip/test2/test-env
verifier:
  name: testinfra
