---
galaxy_info:
  role_name: omniversion shared tasks
  description: Shared tasks used by the `omniversion` roles to parse and save data.
  author: Roman Priebe
  company: Layer9 GmbH
  platforms:
    - name: EL
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: macOS
      versions:
        - all
    - name: MacOSX
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
