---
galaxy_info:
  role_name: audit
  description: Run the `audit` command for each package manager on each host. Available for `npm` and `gem` (if `bundle-audit` is installed).
  author: Roman Priebe
  company: Layer9 GmbH
  platforms:
    - name: EL
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: macOS
      versions:
        - all
    - name: MacOSX
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
  min_ansible_version: 2.5
