---
- name: Get `custom` command output
  ansible.builtin.command: '{{ var_omniversion_custom_command }}' # noqa command-instead-of-shell
  args:
    chdir: '{{ var_omniversion_custom_dir }}'
  register: var_omniversion_custom_result
  changed_when: false
  tags:
    - custom

- name: Remember result
  ansible.builtin.set_fact:
    var_omniversion_custom_parsed_results: >-
      {{ var_omniversion_custom_parsed_results + [{
      "name": var_omniversion_custom_name,
      "version": var_omniversion_custom_result.stdout
      }] }}'
