---
- name: Prepare results
  ansible.builtin.set_fact:
    var_omniversion_custom_parsed_results: []

- name: List `custom` package versions
  with_items: '{{ var_omniversion.custom }}'
  args:
    apply:
      tags:
        - custom
  vars:
    var_omniversion_custom_command: '{{ item.command }}'
    var_omniversion_custom_dir: '{{ item.dir | default("/") }}'
    var_omniversion_custom_name: '{{ item.name }}'
  include_tasks: custom.item.yaml

- name: Save results
  include_tasks: ../../shared/save.yaml
  vars:
    var_omniversion_save_input: "{{ { 'version': var_omniversion_version, 'items': var_omniversion_custom_parsed_results } | to_nice_yaml(indent=2) }}"
