---
- name: Get `go` version info
  ansible.builtin.command: 'go version'
  register: var_omniversion_go_result
  changed_when: false

- include_tasks: ../../shared/parse.yaml
  vars:
    var_omniversion_parse_input: '{{ var_omniversion_go_result.stdout | string }}'

- include_tasks: ../../shared/save.yaml
  vars:
    var_omniversion_save_input: '{{ var_omniversion_parse_result.stdout | string }}'
