---
- name: Set verb to `version`
  ansible.builtin.set_fact:
    var_omniversion_verb: version
  tags:
    - always

- name: Get versions of npm, Node etc.
  when: var_omniversion.npm is defined
  tags:
    - npm
  block:
    - name: Get versions as json
      ansible.builtin.command: 'npm version --json'
      args:
        chdir: '{{ var_omniversion.npm.dir | default("/") }}'
      register: omniversion_result
      changed_when: true

    - include_tasks: ../../shared/save.yaml
      vars:
        var_omniversion_pm: npm

- name: Get versions of specific packages through custom shell commands
  when: var_omniversion.custom is defined
  tags:
    - custom
  with_items: '{{ var_omniversion.custom }}'
  include_tasks: custom.yaml
