---
- name: Set verb to `version`
  ansible.builtin.set_fact:
    var_omniversion_verb: version
  tags:
    - always

- name: Run `npm` tasks
  when: var_omniversion.npm is defined and var_omniversion.npm
  tags:
    - npm
  args:
    apply:
      tags:
        - npm
  vars:
    var_omniversion_pm: npm
  include_tasks: npm.yaml

- name: Run `custom` tasks
  when: var_omniversion.custom is defined and var_omniversion.custom
  tags:
    - custom
  args:
    apply:
      tags:
        - custom
  vars:
    var_omniversion_pm: custom
  include_tasks: custom.yaml
