---
- name: 'pip : Prepare results'
  ansible.builtin.set_fact:
    var_omniversion_pip_parsed_results: []

- name: 'Get version of each `pip` executable'
  loop: '{{ var_omniversion.pip.executables | default(["pip"]) }}'
  loop_control:
    loop_var: var_omniversion_pip_executable
  include_tasks: 'pip.executable.yaml'
  args:
    apply:
      tags:
        - pip

- name: 'Get version of each `pip` executable in virtual environments'
  loop: '{{ var_omniversion.pip.venv | default([]) }}'
  loop_control:
    loop_var: var_omniversion_pip_venv
  include_tasks: 'pip.executable.yaml'
  args:
    apply:
      tags:
        - pip
  vars:
    var_omniversion_pip_executable: '{{ var_omniversion_pip_venv }}/bin/pip'

# we save the results as multiple yaml documents in the same file
- name: 'pip : Save results'
  include_tasks: ../../shared/save.yaml
  vars:
    var_omniversion_save_input: "{{ var_omniversion_pip_parsed_results | join(\"\n---\n\") }}"
