---
- name: 'pip : List available `pip` updates'
  ansible.builtin.command: 'pip --version'
  register: var_omniversion_pip_result
  changed_when: true

- include_tasks: ../../shared/parse.yaml
  vars:
    var_omniversion_parse_input: '{{ var_omniversion_pip_result.stdout | string }}'

- include_tasks: ../../shared/save.yaml
  vars:
    var_omniversion_save_input: '{{ var_omniversion_parse_result.stdout | string }}'
