---
- name: Get `rvm` version info
  ansible.builtin.command: 'bash -lc "rvm --version"'
  register: var_omniversion_rvm_result
  changed_when: false

- include_tasks: ../../shared/parse.yaml
  vars:
    var_omniversion_parse_input: '{{ var_omniversion_rvm_result.stdout | string }}'

- include_tasks: ../../shared/save.yaml
  vars:
    var_omniversion_save_input: '{{ var_omniversion_parse_result.stdout | string }}'
