---
- name: 'file : item : List `file` item package versions'
  ansible.builtin.shell: 'cat {{ var_omniversion_file_item.path }}'
  args:
    chdir: /
  register: var_omniversion_file_item_result
  changed_when: false

- name: 'file : item : Parse result'
  include_tasks: ../../shared/parse.yaml
  vars:
    var_omniversion_parse_input: '{{ var_omniversion_file_item_result.stdout | string }}'
    var_omniversion_pm: raw
    var_omniversion_parse_args: '--name={{ var_omniversion_file_item.name | default("") }} --regex={{ var_omniversion_file_item.regex | default("") | quote }}'

- name: 'file : item : Remember result'
  ansible.builtin.set_fact:
    var_omniversion_file_parsed_results: '{{ var_omniversion_file_parsed_results + [var_omniversion_parse_result.stdout] }}'
