---
- name: 'file : Prepare results'
  ansible.builtin.set_fact:
    var_omniversion_file_parsed_results: []

- name: 'file : List `file` versions'
  when: var_omniversion.file is defined
  loop: '{{ var_omniversion.file }}'
  loop_control:
    loop_var: var_omniversion_file_item
  args:
    apply:
      tags:
        - file
  include_tasks: file.item.yaml

# we save the results as multiple yaml documents in the same file
- name: 'file : Save results'
  include_tasks: ../../shared/save.yaml
  vars:
    var_omniversion_save_input: "{{ (var_omniversion_file_parsed_results | join(\"\n---\n\")) }}"
