---
- name: 'gem : List `gem` versions'
  ansible.builtin.command: 'gem list --details --versions --all'
  args:
    chdir: '{{ var_omniversion.gem.dir | default("/") }}'
  register: var_omniversion_gem_result

- include_tasks: ../../shared/parse.yaml
  vars:
    var_omniversion_parse_input: '{{ var_omniversion_gem_result.stdout | string }}'

- include_tasks: ../../shared/save.yaml
  vars:
    var_omniversion_save_input: '{{ var_omniversion_parse_result.stdout | string }}'
