---
- name: 'go : system : List system `go` packages'
  ansible.builtin.command: 'go list ...'
  args:
    chdir: '/'
  register: var_omniversion_go_system_result
  changed_when: false

- name: 'go : system : Parse result'
  when: var_omniversion.go.system | default(true)
  include_tasks: ../../shared/parse.yaml
  vars:
    var_omniversion_parse_input: '{{ var_omniversion_go_system_result.stdout | string }}'

- name: 'go : system : Remember result'
  ansible.builtin.set_fact:
    var_omniversion_go_parsed_results: '{{ var_omniversion_go_parsed_results + [var_omniversion_parse_result.stdout] }}'
