---
- name: 'go : Prepare results'
  ansible.builtin.set_fact:
    var_omniversion_go_parsed_results: []

- name: 'go : List `go` module versions'
  when: var_omniversion.go.local is defined
  loop: '{{ var_omniversion.go.local }}'
  loop_control:
    loop_var: var_omniversion_go_local_dir
  args:
    apply:
      tags:
        - go
  include_tasks: go.local.yaml

- name: 'go : List system `go` module versions'
  when: var_omniversion.go.system | default(true)
  args:
    apply:
      tags:
        - go
  include_tasks: go.system.yaml

# we save the results as multiple yaml documents in the same file
- name: 'go : Save results'
  include_tasks: ../../shared/save.yaml
  vars:
    var_omniversion_save_input: "{{ (var_omniversion_go_parsed_results | join(\"\n---\n\")) }}"
