---
- name: Set verb to `list`
  ansible.builtin.set_fact:
    var_omniversion_verb: list
  tags:
    - always

- name: 'Run tasks'
  loop:
    - apt
    - gem
    - go
    - npm
    - nvm
    - pip
    - rvm
  loop_control:
    loop_var: pm
  tags:
    - always
  when: pm in var_omniversion and var_omniversion[pm]
  include_tasks: '{{ pm }}.yaml'
  vars:
    var_omniversion_pm: '{{ pm }}'
  args:
    apply:
      tags:
        - '{{ pm }}'
