---
- name: Set verb to `list`
  ansible.builtin.set_fact:
    var_omniversion_verb: list
  tags:
    - always

- name: List and store `apt` versions
  when: var_omniversion.apt is defined and var_omniversion.apt
  tags:
    - apt
  block:
    - name: List apt package versions
      ansible.builtin.shell: 'apt list --installed 2> /dev/null || true'
      register: omniversion_result
      changed_when: true

    - include_tasks: ../../shared/save.yaml
      vars:
        var_omniversion_pm: apt

- name: List and store global `npm` versions
  when: (var_omniversion.npm.global is defined and var_omniversion.npm.global) or var_omniversion.npm.global is not defined
  tags:
    - npm
  include_tasks: npm.global.yaml

- name: List and store local `npm` versions
  when: var_omniversion.npm.local is defined
  with_indexed_items: '{{ var_omniversion.npm.local }}'
  tags:
    - npm
  include_tasks: npm.local.yaml
  vars:
    var_omniversion_result_index: '{{ item.0 }}'
    var_omniversion_dir: '{{ item.1 }}'

- name: List and store rubygems versions
  when: var_omniversion.rubygems is defined
  tags:
    - rubygems
    - gem
  block:
    - name: Fetch gem versions
      ansible.builtin.command: 'gem list --details --versions --all'
      args:
        chdir: '{{ var_omniversion.rubygems.dir }}'
      register: omniversion_result
      changed_when: true

    - include_tasks: ../../shared/save.yaml
      vars:
        var_omniversion_pm: gem

- name: List and store rvm ruby versions
  when: var_omniversion.rvm is defined
  tags:
    - rvm
  block:
    - name: Fetch rvm ruby versions
      ansible.builtin.shell: '/usr/local/rvm/bin/rvm ls' # noqa command-instead-of-shell
      register: omniversion_result
      changed_when: true

    - include_tasks: ../../shared/save.yaml
      vars:
        var_omniversion_pm: rvm
