---
- name: Set verb to `list`
  ansible.builtin.set_fact:
    var_omniversion_verb: list
  tags:
    - always

- name: List and store apt versions
  when: var_omniversion.apt is defined
  tags:
    - apt
  block:
    - name: List apt package versions
      ansible.builtin.shell: 'apt list --installed 2> /dev/null || true'
      register: omniversion_result
      changed_when: true

    - include_tasks: ../../shared/save.yaml
      vars:
        var_omniversion_pm: apt

- name: List and store npm versions
  when: var_omniversion.npm is defined
  tags:
    - npm
  block:
    - name: List npm versions
      ansible.builtin.shell: 'npm ls --parseable 2>&1 || true'
      args:
        chdir: '{{ var_omniversion.npm.dir | default("/") }}'
      register: omniversion_result
      changed_when: true

    - include_tasks: ../../shared/save.yaml
      vars:
        var_omniversion_pm: npm

- name: List and store rubygems versions
  when: var_omniversion.rubygems is defined
  tags:
    - rubygems
    - gem
  block:
    - name: Fetch rubygems versions
      ansible.builtin.command: 'gem list --details --versions --all'
      args:
        chdir: '{{ var_omniversion.rubygems.dir }}'
      register: omniversion_result
      changed_when: true

    - include_tasks: ../../shared/save.yaml
      vars:
        var_omniversion_pm: rubygems

- name: List and store rvm ruby versions
  when: var_omniversion.rvm is defined
  tags:
    - rvm
  block:
    - name: Fetch rvm ruby versions
      ansible.builtin.shell: '/usr/local/rvm/bin/rvm ls' # noqa command-instead-of-shell
      register: omniversion_result
      changed_when: true

    - include_tasks: ../../shared/save.yaml
      vars:
        var_omniversion_pm: rvm
