---
- name: 'npm : local : List local `npm` package versions'
  ansible.builtin.command: bash -ic 'npm ls --json --all'
  args:
    chdir: '{{ var_omniversion_npm_local_dir }}'
  register: var_omniversion_npm_local_result
  changed_when: false

- name: 'npm : local : Parse result'
  include_tasks: ../../shared/parse.yaml
  vars:
    var_omniversion_parse_input: '{{ var_omniversion_npm_local_result.stdout | string }}'

- name: 'npm : local : Remember result'
  ansible.builtin.set_fact:
    var_omniversion_npm_local_parsed_results: '{{ var_omniversion_npm_local_parsed_results + [var_omniversion_parse_result.stdout] }}'
