---
- name: 'pip : global : List packages for executable `{{ var_omniversion_pip_executable }}`'
  ansible.builtin.command: "{{ var_omniversion_pip_executable }} list --format=json"
  register: var_omniversion_pip_global_result
  changed_when: false

- name: 'pip : global : Parse result'
  include_tasks: ../../shared/parse.yaml
  vars:
    var_omniversion_parse_input: '{{ var_omniversion_pip_global_result.stdout | string }}'

- name: 'pip : global : List packages for executable `{{ var_omniversion_pip_executable }}` using legacy freeze format'
  ansible.builtin.command: "{{ var_omniversion_pip_executable }} freeze"
  register: var_omniversion_pip_global_legacy_result
  changed_when: false
  when: var_omniversion_pip_global_result.rc != 0

- name: 'pip : global : Parse legacy result'
  include_tasks: ../../shared/parse.yaml
  vars:
    var_omniversion_parse_input: '{{ var_omniversion_pip_global_legacy_result.stdout | string }}'
  when: var_omniversion_pip_global_result.rc != 0 and var_omniversion_pip_global_legacy_result.rc != 0

- name: 'pip : global : Remember result'
  ansible.builtin.set_fact:
    var_omniversion_pip_global_parsed_results: '{{ var_omniversion_pip_global_parsed_results + [var_omniversion_parse_result.stdout] }}'
