---
- name: 'pip : venv : List `pip` updates in virtual environment'
  ansible.builtin.command: '{{ var_omniversion_pip_executable }} list --format=json --local'
  register: var_omniversion_pip_local_result
  changed_when: false

- name: 'pip : venv : Parse result'
  include_tasks: ../../shared/parse.yaml
  vars:
    var_omniversion_parse_input: '{{ var_omniversion_pip_local_result.stdout | string }}'

- name: 'pip : venv : Remember result'
  ansible.builtin.set_fact:
    var_omniversion_pip_local_parsed_results: '{{ var_omniversion_pip_local_parsed_results + [var_omniversion_parse_result.stdout] }}'
