---
- name: 'gem : List `gem` security advisories'
  ansible.builtin.command: 'bundle-audit 2> /dev/null || true'
  args:
    chdir: '{{ var_omniversion.gem.dir | default("/") }}'
  register: var_omniversion_gem_result
  failed_when: false
  ignore_errors: true
  changed_when: false

- include_tasks: ../../shared/parse.yaml
  vars:
    var_omniversion_parse_input: '{{ var_omniversion_gem_result.stdout | string }}'

- include_tasks: ../../shared/save.yaml
  vars:
    var_omniversion_save_input: '{{ var_omniversion_parse_result.stdout | string }}'
