---
- name: Set verb to `audit`
  ansible.builtin.set_fact:
    var_omniversion_verb: audit
  tags:
    - always

- name: 'gem : Run `gem` tasks'
  when: var_omniversion.gem is defined and var_omniversion.gem
  tags:
    - rubygems
    - gem
  args:
    apply:
      tags:
        - rubygems
        - gem
  vars:
    var_omniversion_pm: gem
  include_tasks: gem.yaml

- name: 'npm : Run `npm` tasks'
  when: var_omniversion.npm is defined and var_omniversion.npm
  tags:
    - npm
  args:
    apply:
      tags:
        - npm
  vars:
    var_omniversion_pm: npm
  include_tasks: npm.yaml
