- name: List global `npm` advisories
  ansible.builtin.shell: 'npm audit -g --prod --json 2>&1 || true'
  register: omniversion_result
  changed_when: true

- name: Save result
  include_tasks: ../../shared/save.yaml
  vars:
    var_omniversion_pm: npm
