---
- name: 'npm : Prepare results'
  ansible.builtin.set_fact:
    var_omniversion_npm_local_parsed_results: []

# `npm audit` does not support testing globals

- name: 'npm : local : List local `npm` security advisories'
  when: var_omniversion.npm.local is defined
  with_items: '{{ var_omniversion.npm.local }}'
  args:
    apply:
      tags:
        - npm
  vars:
    var_omniversion_npm_local_dir: '{{ item }}'
  include_tasks: npm.local.yaml

# we save the results as multiple yaml documents in the same file
- name: 'npm : Save results'
  include_tasks: ../../shared/save.yaml
  vars:
    var_omniversion_save_input: "{{ var_omniversion_npm_local_parsed_results | join(\"\n---\n\") }}"
