---
- name: Ensure omniversion binary is installed
  ansible.builtin.command: "omniversion version"
  register: omniversion_check_result
  ignore_errors: true
  delegate_to: localhost
  changed_when: false
  tags:
    - always

- name: Fail if `omniversion` binary is not installed in localhost
  ansible.builtin.fail:
    msg: "The `omniversion` binary is not installed in your localhost. Please follow this advice to install it: https://github.com/omniversion/omniversion/cli"
  when: omniversion_check_result.rc != 0
  tags:
    - always

- name: Find `omniversion` version
  run_once: true
  delegate_to: localhost
  ansible.builtin.shell: "set -o pipefail && omniversion version | grep version: | sed 's/version: //'"
  register: var_omniversion_version_output
  tags:
    - always
  changed_when: false

- name: Set `omniversion` version
  run_once: true
  delegate_to: localhost
  ansible.builtin.set_fact:
    var_omniversion_version: '{{ var_omniversion_version_output.stdout }}'
  tags:
    - always
