---
galaxy_info:
  role_name: omniversion check role
  description: Check that `omniversion/cli` is installed on the control node.
  author: Roman Priebe
  company: Layer9 GmbH
  platforms:
    - name: EL
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: macOS
      versions:
        - all
    - name: MacOSX
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
