---
galaxy_info:
  role_name: refresh
  description: Refresh/update the cache of each package manager on each host. Available for `apt` only.
  author: Roman Priebe
  company: Layer9 GmbH
  platforms:
    - name: EL
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: macOS
      versions:
        - all
    - name: MacOSX
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
  min_ansible_version: 2.5
