---
- name: Run omniversion `check` role
  include_role: check

- name: Run omniversion `autodetect` role
  include_role: autodetect

- name: Run omniversion `audit` role
  include_role: audit

- name: Run omniversion `list` role
  include_role: list

- name: Run omniversion `outdated` role
  include_role: outdated

- name: Run omniversion `refresh` role
  include_role: refresh

- name: Run omniversion `version` role
  include_role: version
