---
- name: 'apt : List available `apt` updates'
  ansible.builtin.shell: 'apt list --upgradable'
  register: var_omniversion_apt_result

- include_tasks: ../../shared/parse.yaml
  vars:
    var_omniversion_parse_input: '{{ var_omniversion_apt_result.stdout | string }}'

- include_tasks: ../../shared/save.yaml
  vars:
    var_omniversion_save_input: '{{ var_omniversion_parse_result.stdout | string }}'
