---
- name: 'apt : List available `apt` updates'
  ansible.builtin.shell: 'apt list --upgradeable 2> /dev/null || true'
  register: var_omniversion_apt_result
  changed_when: true

- include_tasks: ../../shared/parse.yaml
  vars:
    var_omniversion_parse_input: '{{ var_omniversion_apt_result.stdout | string }}'

- include_tasks: ../../shared/save.yaml
  vars:
    var_omniversion_save_input: '{{ var_omniversion_parse_result.stdout | string }}'
