---
- name: 'go : Prepare results'
  ansible.builtin.set_fact:
    var_omniversion_go_parsed_results: []

- name: 'go : List available `go` module updates'
  when: var_omniversion.go.local is defined
  with_items: '{{ var_omniversion.go.local }}'
  args:
    apply:
      tags:
        - go
  vars:
    var_omniversion_go_local_dir: '{{ item }}'
  include_tasks: go.local.yaml

# we save the results as multiple yaml documents in the same file
- name: 'go : Save results'
  include_tasks: ../../shared/save.yaml
  vars:
    var_omniversion_save_input: "{{ (var_omniversion_go_parsed_results | join(\"\n---\n\")) }}"
