---
- name: Set verb to `outdated`
  ansible.builtin.set_fact:
    var_omniversion_verb: outdated
  tags:
    - always

- name: 'Run tasks'
  loop:
    - apt
    - gem
    - go
    - npm
  loop_control:
    loop_var: pm
  tags:
    - always
  when: pm in var_omniversion and var_omniversion[pm]
  include_tasks: '{{ pm }}.yaml'
  vars:
    var_omniversion_pm: '{{ pm }}'
  args:
    apply:
      tags:
        - '{{ pm }}'

- name: 'Run `pip` tasks'
  tags:
    - pip
  # pip2 does not have an `outdated` command, but pip3 does...
  when: var_omniversion.pip and not (var_omniversion.pip.version2 | default(false))
  include_tasks: pip.yaml
  vars:
    var_omniversion_pm: pip
  args:
    apply:
      tags:
        - pip