---
- name: Set verb to `outdated`
  ansible.builtin.set_fact:
    var_omniversion_verb: outdated
  tags:
    - always

- name: 'apt : Run `apt` tasks'
  when: var_omniversion.apt is defined and var_omniversion.apt
  tags:
    - apt
  args:
    apply:
      tags:
        - apt
  vars:
    var_omniversion_pm: apt
  include_tasks: apt.yaml

- name: 'gem : Run `gem` tasks'
  when: var_omniversion.gem is defined and var_omniversion.gem
  tags:
    - bundle
    - bundler
    - gem
    - rubygems
  args:
    apply:
      tags:
        - bundle
        - bundler
        - gem
        - rubygems
  vars:
    var_omniversion_pm: gem
  include_tasks: gem.yaml

- name: 'npm : Run `npm` tasks'
  when: var_omniversion.npm is defined and var_omniversion.npm
  tags:
    - npm
  args:
    apply:
      tags:
        - npm
  vars:
    var_omniversion_pm: npm
  include_tasks: npm.yaml
