---
- name: 'pip : global : List available updates'
  ansible.builtin.command: '{{ var_omniversion_pip_executable }} list --outdated --format=json'
  register: var_omniversion_pip_global_result
  changed_when: false
  ignore_errors: true

- name: 'pip : global : Parse result'
  include_tasks: ../../shared/parse.yaml
  vars:
    var_omniversion_parse_input: '{{ var_omniversion_pip_global_result.stdout | string }}'
  when: var_omniversion_pip_global_result.rc == 0

- name: 'pip : global : Remember result'
  ansible.builtin.set_fact:
    var_omniversion_pip_global_parsed_results: '{{ var_omniversion_pip_global_parsed_results + [var_omniversion_parse_result.stdout] }}'
  when: var_omniversion_pip_global_result.rc == 0
