---
- name: 'apt : Refresh apt cache'
  when: var_omniversion.apt is defined
  ansible.builtin.command: 'apt update 2> /dev/null || true'
  become: true
  failed_when: false
  changed_when: true
  ignore_errors: true
  tags:
    - apt
