---
- name: 'apt : Refresh `apt` cache'
  when: var_omniversion.apt is defined and var_omniversion.apt
  ansible.builtin.command: 'apt update 2> /dev/null'
  become: true
  changed_when: false
  failed_when: false
  tags:
    - apt

- name: 'gem : Refresh `bundle-audit` cache'
  when: var_omniversion.gem is defined and var_omniversion.gem
  ansible.builtin.command: 'bundle-audit update'
  become: true
  changed_when: false
  failed_when: false
  tags:
    - gem
