---
- name: 'Check for presence of package manager `{{ var_omniversion_pm }}`'
  ansible.builtin.command: '{{ var_omniversion_detect_command }}'
  register: omniversion_check_result
  ignore_errors: true
  failed_when: false
  changed_when: false
  when: var_omniversion[item] is not defined

- name: 'Activate package manager `{{ var_omniversion_pm }}`'
  ansible.builtin.set_fact:
    var_omniversion: '{{ var_omniversion | combine({ var_omniversion_pm: true }) }}'
  when: omniversion_check_result.rc == 0

- name: 'Deactivate package manager `{{ var_omniversion_pm }}`'
  ansible.builtin.set_fact:
    var_omniversion: '{{ var_omniversion | combine({ var_omniversion_pm: false }) }}'
  when: omniversion_check_result.rc != 0
