---
- name: Set default `var_omniversion` value
  tags:
    - always
  ansible.builtin.set_fact:
    var_omniversion: "{{ {'auto': true} | combine(var_omniversion | default({})) }}"

- name: Check for presence of package managers
  tags:
    - always
  args:
    apply:
      tags:
        - always
  include_tasks: detect.yaml
  with_items:
    - name: apt
      command: which apt
    - name: brew
      command: which brew
    - name: npm
      command: which npm
    - name: gem
      command: which gem
    - name: rvm
      command: /bin/bash -l -c 'rvm --version'
  when: var_omniversion.auto and var_omniversion[item.name] is not defined
  vars:
    var_omniversion_pm: '{{ item.name }}'
    var_omniversion_detect_command: '{{ item.command }}'

- name: Show complete configuration after auto-detection
  tags:
    - always
  when: var_omniversion.auto
  debug:
    msg: '{{ var_omniversion }}'
