---
- name: Set default `var_omniversion` value
  tags:
    - always
  ansible.builtin.set_fact:
    var_omniversion: "{{ {'auto': true} | combine(var_omniversion | default({})) }}"

- name: Check for presence of package managers
  tags:
    - always
  args:
    apply:
      tags:
        - always
  include_tasks: detect.yaml
  with_items:
    - name: apt
      command: which apt
    - name: brew
      command: which brew
    - name: gem
      command: bash -lc 'which gem'
    - name: go
      command: which go
    - name: npm
      command: bash -ic 'which npm'
    - name: nvm
      command: bash -ic 'nvm --version'
    - name: rvm
      command: bash -lc 'rvm --version'
  when: var_omniversion.auto and var_omniversion[item.name] is not defined
  vars:
    var_omniversion_pm: '{{ item.name }}'
    var_omniversion_detect_command: '{{ item.command }}'

- name: Check for presence of `pip`
  tags:
    - pip
  args:
    apply:
      tags:
        - pip
  include_tasks: pip.yaml
  when: var_omniversion.auto and var_omniversion["pip"] is not defined
  vars:
    var_omniversion_pm: pip

- name: Show complete configuration after auto-detection
  tags:
    - always
  when: var_omniversion.auto
  ansible.builtin.debug:
    msg: '{{ var_omniversion }}'
