---
- name: Run all roles
  tags:
    - always
  block:
    - name: Run all roles in turn
      include_role:
        name: '{{ role }}'
      loop:
        - check
        - autodetect
        - audit
        - list
        - outdated
        - refresh
        - version
      loop_control:
        loop_var: role
