---
galaxy_info:
  role_name: omniversion outdated role
  description: Run the `oudated` command for each package manager on each host. Available for `apt`, `gem`, `go`, `npm`, and `pip`.
  author: Roman Priebe
  company: Layer9 GmbH
  platforms:
    - name: EL
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: macOS
      versions:
        - all
    - name: MacOSX
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
