---
- name: Determine output directory
  ansible.builtin.set_fact:
    var_omniversion_full_output_dir: "{{ var_omniversion_output_dir | default('.') }}/{{ inventory_hostname }}/{{ var_omniversion_pm }}"

- name: Ensure output directory exists
  ansible.builtin.file:
    path: "{{ var_omniversion_full_output_dir }}"
    state: directory
    mode: '777'
  delegate_to: localhost

- name: Remove previous results
  ansible.builtin.copy:
    dest: "{{ var_omniversion_full_output_dir }}/{{ var_omniversion_verb }}.omniversion.yaml"
    content: ""
    mode: '777'
  delegate_to: localhost

- name: Parse output
  ansible.builtin.command: "omniversion parse {{ var_omniversion_pm }}"
  args:
    stdin: "{{ omniversion_result.stdout | string }}"
  delegate_to: localhost
  register: omniversion_result
  changed_when: true
  ignore_errors: true

- name: Log error
  ansible.builtin.debug:
    msg: "{{ omniversion_result.stderr }}"
  when: omniversion_result.stderr

- name: Store parsed result
  ansible.builtin.copy:
    dest: "{{ var_omniversion_full_output_dir }}/{{ var_omniversion_verb }}.omniversion.yaml"
    content: "{{ omniversion_result.stdout }}"
    mode: '777'
  delegate_to: localhost
