---
- name: '{{ var_omniversion_pm }} : Determine output directory'
  ansible.builtin.set_fact:
    var_omniversion_save_dir: "{{ var_omniversion_output_dir | default('/tmp/omniversion') }}/{{ inventory_hostname }}/{{ var_omniversion_pm }}"

- name: '{{ var_omniversion_pm }} : Determine output file'
  set_fact:
    var_omniversion_save_file: "{{ var_omniversion_save_dir }}/{{ var_omniversion_verb }}.omniversion.yaml"

- name: '{{ var_omniversion_pm }} : Ensure directory exists'
  ansible.builtin.file:
    path: "{{ var_omniversion_save_dir }}"
    state: directory
    mode: '777'
  delegate_to: localhost

- name: '{{ var_omniversion_pm }} : Remove previous results'
  ansible.builtin.copy:
    dest: '{{ var_omniversion_save_file }}'
    content: ""
    mode: '777'
  delegate_to: localhost

- name: '{{ var_omniversion_pm }} : Store result'
  ansible.builtin.copy:
    dest: "{{ var_omniversion_save_file }}"
    content: '{{ var_omniversion_save_input }}'
    mode: '777'
  delegate_to: localhost
