name: Publish Ansible Galaxy collection

on:
  push:
    tags:
      - '*'

jobs:
  publish_to_ansible_galaxy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Extract version from tag (e.g. `/refs/tags/v0.1.2` -> `0.1.2`)
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/v}

      - name: Build and Deploy Collection
        uses: artis3n/ansible_galaxy_collection@v2
        with:
          api_key: '${{ secrets.GALAXY_API_KEY }}'
          galaxy_version: '${{ steps.get_version.outputs.VERSION }}'
          collection_dir: ansible
