name: Upload code coverage

on:
  push:
    branches:
      - main

jobs:
  codecov:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      -
        name: Go test
        working-directory: cli
        run: go test ./... -coverprofile=test/coverage.out

      - name: Set up python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        working-directory: python
        run: pip3 install -r requirements.txt

      - name: Install test dependencies
        working-directory: python
        run: pip3 install pytest pytest-cov

      - name: Python test
        working-directory: python
        run: python3 -m pytest --cov=omniversion --cov-report=xml test_omniversion

      -
        name: Upload coverage
        uses: codecov/codecov-action@v2
        with:
          files: ./cli/test/coverage.out,./python/coverage.xml
