name: Release

on:
  push:
    tags:
      - '*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      -
        name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.OMNIVERSION_RELEASE_ACTION_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
      -
        name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.OMNIVERSION_RELEASE_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.OMNIVERSION_RELEASE_GPG_PASSPHRASE }}
      -
        name: Generate repo shasum
        run: echo "OMNIVERSION_INSTALL_SHASUM=$(tar -cf - cli | shasum | sed 's/[^0-9a-f]*//g' | tr -d '\\n')" >> $GITHUB_ENV
      -
        name: Run GoReleaser
        id: goreleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          workdir: cli
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.OMNIVERSION_RELEASE_ACTION_TOKEN }}
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
      -
        name: Create Packages file
        run: dpkg-scanpackages -m dist | gzip -c > dist/Packages.gz
      -
        name: Upload Packages file
        id: upload-packages-file
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.OMNIVERSION_RELEASE_ACTION_TOKEN }}
        with:
          files: dist/Packages.gz
      - uses: actions/setup-node@v1
      - name: Publish
        run: |
          npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
          npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}