name: Publish Python module

on:
  push:
    tags:
      - '*'

jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        working-directory: python
        run: pip3 install -r requirements.txt

      - name: Generate documentation
        working-directory: python
        run: pdoc omniversion --html --output-dir docs

      - name: Extract version from tag (e.g. `/refs/tags/v0.1.2` -> `0.1.2`)
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/v}

      - name: Create PyPi package
        working-directory: python
        run: VERSION=${{ steps.get_version.outputs.VERSION }} python3 -m build

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages_dir: python/dist/
